
title:               "Deepanshu's scratchpad"
tagline:             'over come the unseen force that stands in the way of true inspiration'
description:         'Beliver in self learning , break it to make it'
url:                 https://deepskandpal.github.io/
baseurl:             ''
paginate:            5
future:              true

# About/contact
author:
  name:              Deepanshu Kandpal
  url:               https://twitter.com/atdeepanshu
  email:             dkandpalz@gmail.com

# Custom vars
version:             0.0.1

# Google Analytics
analytics:
  provider               : google
  google:
    tracking_id          : 'UA-123173812-1'

plugins:
  - jekyll-paginate
  - jemoji
